/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RoundingJNI */

#ifndef _Included_RoundingJNI
#define _Included_RoundingJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RoundingJNI
 * Method:    round_down
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_RoundingJNI_round_1down
  (JNIEnv *, jobject);

/*
 * Class:     RoundingJNI
 * Method:    round_up
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_RoundingJNI_round_1up
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
